matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: node_js
      node_js:
        - "6"
      cache:
        directories:
        - node_modules
        - app/node_modules
        - $HOME/.electron
        - $HOME/.cache
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull electronuserland/electron-builder:wine

branches:
  only:
    - master
    - develop

script:
  - bash ./bin/travis.sh
