matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: node_js
      node_js:
        - "6"
      before_install:
        - brew install jq
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - jq
      services:
        - docker
      before_install:
        - docker pull electronuserland/electron-builder:wine

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

branches:
  only:
    - master
    - develop
script:
  - bash ./bin/travis.sh
