osx_image: xcode7.3
sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

matrix:
  include:
    - os: osx
    - os: linux
      services:
        - docker
      before_install:
        - docker pull electronuserland/electron-builder:wine

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache
